---
- name: Reset antigen cache
  command: "{{ zsh_path_to_shell }} -c 'source {{ zsh_config }}; antigen reset'"
  become: yes
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false

# it will fail, but it install all bundles for user
- name: Update antigen bundles
  command: "{{ zsh_path_to_shell }} -c 'source {{ zsh_config }}; antigen update'"
  become: yes
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
